/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthNewVerificationIndexRouteImport } from './routes/_auth/new-verification/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthNewPasswordTokenRouteImport } from './routes/_auth/new-password/$token'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewVerificationIndexRoute =
  AuthNewVerificationIndexRouteImport.update({
    id: '/new-verification/',
    path: '/new-verification/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewPasswordTokenRoute = AuthNewPasswordTokenRouteImport.update({
  id: '/new-password/$token',
  path: '/new-password/$token',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-password/$token': typeof AuthNewPasswordTokenRoute
  '/login/': typeof AuthLoginIndexRoute
  '/new-verification/': typeof AuthNewVerificationIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-password/$token': typeof AuthNewPasswordTokenRoute
  '/login': typeof AuthLoginIndexRoute
  '/new-verification': typeof AuthNewVerificationIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/new-password/$token': typeof AuthNewPasswordTokenRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/new-verification/': typeof AuthNewVerificationIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new-password/$token'
    | '/login/'
    | '/new-verification/'
    | '/register/'
    | '/reset-password/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new-password/$token'
    | '/login'
    | '/new-verification'
    | '/register'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/new-password/$token'
    | '/_auth/login/'
    | '/_auth/new-verification/'
    | '/_auth/register/'
    | '/_auth/reset-password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/new-verification/': {
      id: '/_auth/new-verification/'
      path: '/new-verification'
      fullPath: '/new-verification/'
      preLoaderRoute: typeof AuthNewVerificationIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/new-password/$token': {
      id: '/_auth/new-password/$token'
      path: '/new-password/$token'
      fullPath: '/new-password/$token'
      preLoaderRoute: typeof AuthNewPasswordTokenRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthNewPasswordTokenRoute: typeof AuthNewPasswordTokenRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthNewVerificationIndexRoute: typeof AuthNewVerificationIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNewPasswordTokenRoute: AuthNewPasswordTokenRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthNewVerificationIndexRoute: AuthNewVerificationIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
