/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthNewVerificationIndexRouteImport } from './routes/auth/new-verification/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNewVerificationIndexRoute =
  AuthNewVerificationIndexRouteImport.update({
    id: '/auth/new-verification/',
    path: '/auth/new-verification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/new-verification/': typeof AuthNewVerificationIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/new-verification': typeof AuthNewVerificationIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/new-verification/': typeof AuthNewVerificationIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login/'
    | '/auth/new-verification/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/login' | '/auth/new-verification' | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/auth/login/'
    | '/auth/new-verification/'
    | '/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthNewVerificationIndexRoute: typeof AuthNewVerificationIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/new-verification/': {
      id: '/auth/new-verification/'
      path: '/auth/new-verification'
      fullPath: '/auth/new-verification/'
      preLoaderRoute: typeof AuthNewVerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthNewVerificationIndexRoute: AuthNewVerificationIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
